version: '3.4'

services:
  identifier:
    ports:
      - "80:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    ports:
      - "8890:8890"
    restart: "no"
  resource:
    restart: "no"    
  besluit-publicatie:
    restart: "no"
  download-url:
    restart: "no"    
  harvest-collector:
    restart: "no"    
