version: '3.4'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.6.1
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource:
    image: semtech/mu-cl-resources:1.17.1
    volumes:
      - ./config/resources:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  besluit-publicatie:
    image: lblod/besluit-publicatie-publish-service:0.2.0
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  download-url:
    image: lblod/download-url-service:0.0.5
    environment:
      CACHING_MAX_RETRIES: 300
      CACHING_CRON_PATTERN: '0 */15 * * * *'
      MAX_PENDING_TIME_IN_SECONDS: 7200
    volumes:
      - ./data/files:/data/files
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  harvest-collector:
    image: lblod/harvest-collector-service:0.0.1
    volumes:
      - ./data/files:/share      
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
